<a href="https://colab.research.google.com/github/saicharangowd40-ops/prod-tech/blob/main/Prod_tech_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import numpy as np

print("======================================")
print("     FACTORY PRODUCTION PLANNER")
print("======================================")

# Input: machine hours available
print("\nEnter available hours for each machine:")
m1 = float(input("Machine 1 hours: "))
m2 = float(input("Machine 2 hours: "))
m3 = float(input("Machine 3 hours: "))

# Input: time required by each product on each machine
print("\nEnter machine hours required for each product:")

print("\nProduct 1:")
p1_m1 = float(input("Machine 1: "))
p1_m2 = float(input("Machine 2: "))
p1_m3 = float(input("Machine 3: "))

print("\nProduct 2:")
p2_m1 = float(input("Machine 1: "))
p2_m2 = float(input("Machine 2: "))
p2_m3 = float(input("Machine 3: "))

print("\nProduct 3:")
p3_m1 = float(input("Machine 1: "))
p3_m2 = float(input("Machine 2: "))
p3_m3 = float(input("Machine 3: "))

# Coefficient matrix A
A = np.array([
    [p1_m1, p2_m1, p3_m1],
    [p1_m2, p2_m2, p3_m2],
    [p1_m3, p2_m3, p3_m3]
], dtype=float)

# Available machine hours B
B = np.array([m1, m2, m3], dtype=float)

# Augmented matrix [A | B]
AB = np.column_stack((A, B))

# Calculate ranks
rank_A = np.linalg.matrix_rank(A)
rank_AB = np.linalg.matrix_rank(AB)

print("\n======================================")
print("MATHEMATICAL MODEL")
print("======================================")

print("\nCoefficient Matrix A:")
print(A)

print("\nAvailable Hours Matrix B:")
print(B)

print("\nAugmented Matrix [A | B]:")
print(AB)

print("\nRank of A =", rank_A)
print("Rank of [A|B] =", rank_AB)

# Check consistency
if rank_A == rank_AB:
    print("\nRESULT: The system is CONSISTENT.")

    # Solve AX = B
    if rank_A == 3:
        X = np.linalg.solve(A, B)

        print("\nProduction quantities:")
        print("Product 1 =", round(X[0], 2))
        print("Product 2 =", round(X[1], 2))
        print("Product 3 =", round(X[2], 2))

        # Check for negative production
        if np.any(X < 0):
            print("\nWARNING:")
            print("The mathematical solution contains negative production.")
            print("This is not physically meaningful in a factory.")

        # Calculate machine usage
        usage = A @ X

        print("\nMachine usage:")
        for i in range(3):
            print(
                f"Machine {i+1}: "
                f"{usage[i]:.2f} / {B[i]:.2f} hours"
            )

    else:
        print("\nThe system has infinitely many solutions.")
        print("Additional production constraints are required.")

else:
    print("\nRESULT: The system is INCONSISTENT.")
    print("The available machine hours cannot satisfy all equations.")

    print("\nPossible bottleneck machines:")

    # Test each machine equation against the other two
    for i in range(3):
        other = [j for j in range(3) if j != i]

        A_reduced = A[other, :]
        B_reduced = B[other]

        if np.linalg.matrix_rank(A_reduced) == \
           np.linalg.matrix_rank(
               np.column_stack((A_reduced, B_reduced))
           ):

            print(f"Machine {i+1} may be the bottleneck.")

print("\n======================================")
print("          END OF PROGRAM")
print("======================================")

     FACTORY PRODUCTION PLANNER

Enter available hours for each machine:
Machine 1 hours: 8
Machine 2 hours: 8
Machine 3 hours: 8

Enter machine hours required for each product:

Product 1:
Machine 1: 4
Machine 2: 4
Machine 3: 4

Product 2:
Machine 1: 4
Machine 2: 7
Machine 3: 8

Product 3:
Machine 1: 6
Machine 2: 9
Machine 3: 3

MATHEMATICAL MODEL

Coefficient Matrix A:
[[4. 4. 6.]
 [4. 7. 9.]
 [4. 8. 3.]]

Available Hours Matrix B:
[8. 8. 8.]

Augmented Matrix [A | B]:
[[4. 4. 6. 8.]
 [4. 7. 9. 8.]
 [4. 8. 3. 8.]]

Rank of A = 3
Rank of [A|B] = 3

RESULT: The system is CONSISTENT.

Production quantities:
Product 1 = 2.0
Product 2 = 0.0
Product 3 = 0.0

Machine usage:
Machine 1: 8.00 / 8.00 hours
Machine 2: 8.00 / 8.00 hours
Machine 3: 8.00 / 8.00 hours

          END OF PROGRAM
